// Copyright (c) 2026 ilyskyo
// SPDX-License-Identifier: MIT

package com.ilyskyo.wordlens.data.repository

import android.content.Context
import android.util.Log
import com.ilyskyo.wordlens.data.model.Lang
import com.ilyskyo.wordlens.data.model.LexiconEntry
import com.ilyskyo.wordlens.data.model.LexiconFile
import com.ilyskyo.wordlens.data.model.LexiconIndex
import com.ilyskyo.wordlens.data.store.WordLensJson
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Loads the dictionaries and answers "what could this be?".
 *
 * Two layers, user over built-in:
 *
 * ```
 * assets/lexicon/<lang>.json     shipped with the app, regenerated by tools/build_lexicon.py
 * filesDir/lexicon/<lang>.json   the user's own additions and corrections — these win
 * ```
 *
 * The user layer exists because the honest failure mode of on-device recognition is "I do not
 * know this object". Letting someone add `荞麦面 -> soba` themselves turns that dead end into
 * the app's main growth path, and keeps the data in a file they can read, diff and share.
 */
class LexiconRepository(
    private val context: Context,
    private val scope: CoroutineScope,
) {
    private val _index = MutableStateFlow(LexiconIndex(emptyList()))
    val index: StateFlow<LexiconIndex> = _index.asStateFlow()

    /** Set when a dictionary file failed to parse, surfaced in Settings rather than swallowed. */
    val loadWarnings: StateFlow<List<String>> get() = _warnings
    private val _warnings = MutableStateFlow<List<String>>(emptyList())

    fun loadAsync() {
        scope.launch(Dispatchers.IO) { reload() }
    }

    /** Re-read every dictionary file and rebuild the index. Returns the entry count. */
    suspend fun reload(): Int = withContext(Dispatchers.IO) {
        val warnings = mutableListOf<String>()
        val merged = LinkedHashMap<String, LexiconEntry>()

        for ((source, text) in readAssets()) {
            readLexiconFile(source, text)?.forEach { entry ->
                merged[entry.id] = entry
            } ?: warnings.add("$source could not be parsed")
        }

        val userDir = userDir()
        userDir.listFiles { f -> f.isFile && f.name.endsWith(".json") }
            ?.sortedBy { it.name }
            ?.forEach { file ->
                readLexiconFile(file.name, file.readTextOrNullCompat())?.forEach { entry ->
                    // User entries deliberately shadow built-ins with the same id.
                    merged[entry.id] = entry
                } ?: warnings.add("${file.name} could not be parsed")
            }

        _warnings.value = warnings
        val built = LexiconIndex(merged.values.toList())
        _index.value = built
        Log.i(TAG, "Lexicon ready: ${merged.size} entries, ${warnings.size} warning(s)")
        merged.size
    }

    // ── queries ──────────────────────────────────────────────────────────────

    fun byId(id: String): LexiconEntry? = _index.value.byId(id)

    fun search(query: String, language: Lang? = null, limit: Int = 50): List<LexiconEntry> =
        _index.value.search(query, language, limit)

    fun all(language: Lang? = null): List<LexiconEntry> =
        _index.value.entries.filter { language == null || it.words.containsKey(language.tag) }

    // ── user layer ───────────────────────────────────────────────────────────

    /**
     * Insert or replace a user entry.
     *
     * Written to one file per language so the export is a plain folder of small JSON documents
     * a person can actually open, rather than one giant generated blob.
     */
    suspend fun saveUserEntry(entry: LexiconEntry): Boolean = withContext(Dispatchers.IO) {
        try {
            val lang = Lang.fromAnyTag(entry.primaryLanguage) ?: Lang.ENGLISH
            val file = userFile(lang)
            val existing = readLexiconFile(file.name, file.readTextOrNullCompat())
            val entries = existing.orEmpty().filterNot { it.id == entry.id } + entry
            file.parentFile?.mkdirs()
            file.writeText(
                WordLensJson.instance.encodeToString(
                    LexiconFile.serializer(),
                    LexiconFile(schemaVersion = 1, language = lang.tag, entries = entries.sortedBy { it.headword }),
                ),
                Charsets.UTF_8,
            )
            reload()
            true
        } catch (e: Exception) {
            Log.e(TAG, "saveUserEntry failed for ${entry.id}", e)
            false
        }
    }

    /** Remove a user entry. Built-in entries cannot be deleted, only shadowed. */
    suspend fun deleteUserEntry(id: String): Boolean = withContext(Dispatchers.IO) {
        var changed = false
        userDir().listFiles { f -> f.isFile && f.name.endsWith(".json") }?.forEach { file ->
            val entries = readLexiconFile(file.name, file.readTextOrNullCompat()) ?: return@forEach
            val kept = entries.filterNot { it.id == id }
            if (kept.size != entries.size) {
                changed = true
                file.writeText(
                    WordLensJson.instance.encodeToString(
                        LexiconFile.serializer(),
                        LexiconFile(schemaVersion = 1, language = entries.firstOrNull()?.primaryLanguage ?: "en", entries = kept),
                    ),
                    Charsets.UTF_8,
                )
            }
        }
        if (changed) reload()
        changed
    }

    /** Absolute paths of the user layer, for the "share my words" action. */
    fun userDirectory(): File = userDir()

    // ── internals ────────────────────────────────────────────────────────────

    private fun userDir(): File = File(context.filesDir, "lexicon").apply { mkdirs() }

    private fun userFile(lang: Lang): File = File(userDir(), "user-${lang.tag}.json")

    /**
     * Read every `assets/lexicon` JSON document as `(fileName, text)` pairs.
     *
     * Goes through `open()` rather than `openFd()` on purpose: a lexicographic file is text and
     * compresses well, and `openFd` throws for compressed assets, so it would work in debug and
     * break in release.
     */
    private fun readAssets(): List<Pair<String, String>> = try {
        context.assets.list("lexicon")
            ?.filter { it.endsWith(".json") }
            ?.sorted()
            ?.mapNotNull { name ->
                runCatching {
                    context.assets.open("lexicon/$name").use { it.readBytes().toString(Charsets.UTF_8) }
                }.getOrNull()?.let { name to it }
            }
            .orEmpty()
    } catch (e: Exception) {
        Log.w(TAG, "Cannot list assets/lexicon", e)
        emptyList()
    }

    private fun readLexiconFile(source: String, text: String?): List<LexiconEntry>? {
        if (text.isNullOrBlank()) return emptyList()
        return try {
            WordLensJson.instance.decodeFromString(LexiconFile.serializer(), text).entries
        } catch (e: Exception) {
            Log.e(TAG, "Failed to parse lexicon $source: ${e.message}")
            null
        }
    }

    private companion object {
        const val TAG = "LexiconRepo"

        /** A missing file is not an error worth crashing over; an unreadable one is. */
        fun File.readTextOrNullCompat(): String? = try {
            if (exists()) readText(Charsets.UTF_8) else null
        } catch (e: Exception) {
            Log.w(TAG, "could not read ${name}: ${e.message}")
            null
        }
    }
}
